services:
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=postgres://postgres:secret@database/postgres
    ports:
      - "3000:3000"
  frontend:
    build: frontend
    ports:
    - "80:80"
    depends_on:
      - backend
  database:
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      interval: 1s
      test: "pg_isready --username=postgres"
    image: postgres
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./data:/var/lib/postgresql/data